In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from keras import Input
from keras.models import Sequential
from keras.layers import  Dense, Dropout, Conv2D, Flatten, GlobalMaxPooling2D, MaxPooling2D, Input, BatchNormalization, AveragePooling2D
import json
import pandas as pd
import gc
from IPython.display import clear_output

In [2]:
x_train = np.load('x_train.npy')
y_train = np.load('y_train.npy')
x_test = np.load('x_test.npy')
y_test = np.load('y_test.npy')

In [3]:
feature_shape = x_train[0].shape

In [5]:
x_test.shape

(26032, 32, 32, 3)

In [30]:
df = pd.DataFrame(columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse'],dtype='float64')
df2 = pd.DataFrame(columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse'],dtype='float64')

In [31]:
model = Sequential()


model.add(Conv2D(32, (3, 3), activation='relu', padding='same',input_shape=feature_shape))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
 
model.add(Dense(256, activation='relu'))
model.add(Dense(256, activation='relu'))

 
model.add(Dense(10, activation='softmax'))


model.summary()
opt = tf.keras.optimizers.Adam(learning_rate=1e-5)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['acc','mae','mse'])

score = model.fit(x_train, y_train, epochs=30, batch_size=100 ,validation_data=(x_test, y_test), verbose=2)

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_36 (Conv2D)           (None, 32, 32, 32)        896
_________________________________________________________________
batch_normalization_18 (Batc (None, 32, 32, 32)        128
_________________________________________________________________
conv2d_37 (Conv2D)           (None, 32, 32, 32)        9248
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 16, 16, 32)        0
_________________________________________________________________
flatten_18 (Flatten)         (None, 8192)              0
_________________________________________________________________
dense_46 (Dense)             (None, 256)               2097408
_________________________________________________________________
dense_47 (Dense)             (None, 256)               65792
_________________________________________________________________
dense_48 (Dense)             (None, 10)                2570
=================================================================
Total params: 2,176,042
Trainable params: 2,175,978
Non-trainable params: 64
_________________________________________________________________
Epoch 1/30
733/733 - 10s - loss: 2.0142 - acc: 0.3093 - mae: 0.1678 - mse: 0.0816 - val_loss: 1.7083 - val_acc: 0.4383 - val_mae: 0.1524 - val_mse: 0.0715
Epoch 2/30
733/733 - 9s - loss: 1.3069 - acc: 0.6226 - mae: 0.1264 - mse: 0.0558 - val_loss: 1.0881 - val_acc: 0.7047 - val_mae: 0.1090 - val_mse: 0.0468
Epoch 3/30
733/733 - 9s - loss: 0.8913 - acc: 0.7562 - mae: 0.0912 - mse: 0.0384 - val_loss: 0.8514 - val_acc: 0.7635 - val_mae: 0.0849 - val_mse: 0.0366
Epoch 4/30
733/733 - 9s - loss: 0.7143 - acc: 0.8031 - mae: 0.0730 - mse: 0.0307 - val_loss: 0.7355 - val_acc: 0.7913 - val_mae: 0.0709 - val_mse: 0.0314
Epoch 5/30
733/733 - 9s - loss: 0.6235 - acc: 0.8258 - mae: 0.0628 - mse: 0.0267 - val_loss: 0.6841 - val_acc: 0.8062 - val_mae: 0.0642 - val_mse: 0.0291
Epoch 6/30
733/733 - 9s - loss: 0.5671 - acc: 0.8413 - mae: 0.0564 - mse: 0.0242 - val_loss: 0.6520 - val_acc: 0.8164 - val_mae: 0.0604 - val_mse: 0.0275
Epoch 7/30
733/733 - 9s - loss: 0.5282 - acc: 0.8525 - mae: 0.0520 - mse: 0.0225 - val_loss: 0.6313 - val_acc: 0.8235 - val_mae: 0.0572 - val_mse: 0.0266
Epoch 8/30
733/733 - 9s - loss: 0.4981 - acc: 0.8607 - mae: 0.0487 - mse: 0.0212 - val_loss: 0.6076 - val_acc: 0.8282 - val_mae: 0.0536 - val_mse: 0.0255
Epoch 9/30
733/733 - 9s - loss: 0.4740 - acc: 0.8673 - mae: 0.0462 - mse: 0.0201 - val_loss: 0.5849 - val_acc: 0.8379 - val_mae: 0.0513 - val_mse: 0.0243
Epoch 10/30
733/733 - 9s - loss: 0.4545 - acc: 0.8724 - mae: 0.0441 - mse: 0.0193 - val_loss: 0.5835 - val_acc: 0.8354 - val_mae: 0.0500 - val_mse: 0.0243
Epoch 11/30
733/733 - 9s - loss: 0.4365 - acc: 0.8781 - mae: 0.0423 - mse: 0.0185 - val_loss: 0.5836 - val_acc: 0.8367 - val_mae: 0.0500 - val_mse: 0.0243
Epoch 12/30
733/733 - 9s - loss: 0.4216 - acc: 0.8828 - mae: 0.0407 - mse: 0.0178 - val_loss: 0.5656 - val_acc: 0.8393 - val_mae: 0.0469 - val_mse: 0.0235
Epoch 13/30
733/733 - 9s - loss: 0.4068 - acc: 0.8862 - mae: 0.0393 - mse: 0.0172 - val_loss: 0.5505 - val_acc: 0.8468 - val_mae: 0.0464 - val_mse: 0.0228
Epoch 14/30
733/733 - 9s - loss: 0.3954 - acc: 0.8892 - mae: 0.0382 - mse: 0.0167 - val_loss: 0.5565 - val_acc: 0.8429 - val_mae: 0.0463 - val_mse: 0.0230
Epoch 15/30
733/733 - 9s - loss: 0.3829 - acc: 0.8936 - mae: 0.0371 - mse: 0.0161 - val_loss: 0.5460 - val_acc: 0.8475 - val_mae: 0.0449 - val_mse: 0.0225
Epoch 16/30
733/733 - 9s - loss: 0.3721 - acc: 0.8976 - mae: 0.0360 - mse: 0.0157 - val_loss: 0.5360 - val_acc: 0.8524 - val_mae: 0.0439 - val_mse: 0.0220
Epoch 17/30
733/733 - 9s - loss: 0.3607 - acc: 0.9004 - mae: 0.0351 - mse: 0.0152 - val_loss: 0.5289 - val_acc: 0.8534 - val_mae: 0.0426 - val_mse: 0.0217
Epoch 18/30
733/733 - 9s - loss: 0.3515 - acc: 0.9026 - mae: 0.0342 - mse: 0.0148 - val_loss: 0.5339 - val_acc: 0.8509 - val_mae: 0.0425 - val_mse: 0.0218
Epoch 19/30
733/733 - 9s - loss: 0.3422 - acc: 0.9059 - mae: 0.0334 - mse: 0.0144 - val_loss: 0.5267 - val_acc: 0.8569 - val_mae: 0.0420 - val_mse: 0.0214
Epoch 20/30
733/733 - 9s - loss: 0.3334 - acc: 0.9077 - mae: 0.0326 - mse: 0.0140 - val_loss: 0.5387 - val_acc: 0.8534 - val_mae: 0.0426 - val_mse: 0.0219
Epoch 21/30
733/733 - 9s - loss: 0.3253 - acc: 0.9106 - mae: 0.0319 - mse: 0.0137 - val_loss: 0.5295 - val_acc: 0.8549 - val_mae: 0.0416 - val_mse: 0.0215
Epoch 22/30
733/733 - 9s - loss: 0.3173 - acc: 0.9126 - mae: 0.0312 - mse: 0.0133 - val_loss: 0.5295 - val_acc: 0.8554 - val_mae: 0.0409 - val_mse: 0.0215
Epoch 23/30
733/733 - 9s - loss: 0.3090 - acc: 0.9156 - mae: 0.0304 - mse: 0.0130 - val_loss: 0.5189 - val_acc: 0.8590 - val_mae: 0.0403 - val_mse: 0.0209
Epoch 24/30
733/733 - 9s - loss: 0.3013 - acc: 0.9174 - mae: 0.0298 - mse: 0.0126 - val_loss: 0.5204 - val_acc: 0.8583 - val_mae: 0.0397 - val_mse: 0.0209
Epoch 25/30
733/733 - 9s - loss: 0.2936 - acc: 0.9205 - mae: 0.0291 - mse: 0.0123 - val_loss: 0.5134 - val_acc: 0.8618 - val_mae: 0.0392 - val_mse: 0.0206
Epoch 26/30
733/733 - 9s - loss: 0.2867 - acc: 0.9216 - mae: 0.0285 - mse: 0.0120 - val_loss: 0.5202 - val_acc: 0.8581 - val_mae: 0.0392 - val_mse: 0.0208
Epoch 27/30
733/733 - 9s - loss: 0.2802 - acc: 0.9245 - mae: 0.0280 - mse: 0.0117 - val_loss: 0.5144 - val_acc: 0.8604 - val_mae: 0.0382 - val_mse: 0.0206
Epoch 28/30
733/733 - 9s - loss: 0.2730 - acc: 0.9255 - mae: 0.0274 - mse: 0.0115 - val_loss: 0.5150 - val_acc: 0.8616 - val_mae: 0.0379 - val_mse: 0.0205
Epoch 29/30
733/733 - 9s - loss: 0.2663 - acc: 0.9284 - mae: 0.0267 - mse: 0.0112 - val_loss: 0.5084 - val_acc: 0.8641 - val_mae: 0.0374 - val_mse: 0.0201
Epoch 30/30
733/733 - 10s - loss: 0.2598 - acc: 0.9303 - mae: 0.0262 - mse: 0.0109 - val_loss: 0.5128 - val_acc: 0.8624 - val_mae: 0.0378 - val_mse: 0.0203

In [32]:
newRow = [0.0]
newRow.append(score.history['loss'][29])
newRow.append(score.history['acc'][29])
newRow.append(score.history['mae'][29])
newRow.append(score.history['mse'][29])
newRow.append(score.history['val_loss'][29])
newRow.append(score.history['val_acc'][29])
newRow.append(score.history['val_mae'][29])
newRow.append(score.history['val_mse'][29])

newDF = pd.DataFrame([newRow],columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse']) 
df = pd.concat([df,newDF])

del(newRow)
del(newDF)
gc.collect()

newRow = [0.0]
newRow.append(score.history['loss'][-1])
newRow.append(score.history['acc'][-1])
newRow.append(score.history['mae'][-1])
newRow.append(score.history['mse'][-1])
newRow.append(score.history['val_loss'][-1])
newRow.append(score.history['val_acc'][-1])
newRow.append(score.history['val_mae'][-1])
newRow.append(score.history['val_mse'][-1])

newDF = pd.DataFrame([newRow],columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse']) 
df2 = pd.concat([df2,newDF])

del(model)
del(score)
del(newRow)
del(newDF)
gc.collect()

16218

35670

In [33]:
df

,dropout,loss,acc,mae,mse,val_loss,val_acc,val_mae,val_mse
0,0.0,0.259787,0.930314,0.026198,0.010878,0.512817,0.862439,0.037774,0.020318

In [34]:
count = 1
for i in [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]:

    model = Sequential()


    model.add(Conv2D(32, (3, 3), activation='relu', padding='same',input_shape=feature_shape))
    model.add(BatchNormalization())
    model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2)))

    model.add(Flatten())

    model.add(Dense(256, activation='relu'))
    model.add(Dropout(i))
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(i))


    model.add(Dense(10, activation='softmax'))

    opt = tf.keras.optimizers.Adam(learning_rate=1e-5)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['acc','mae','mse'])

    score = model.fit(x_train, y_train, epochs=30+int(30*i), batch_size=100 ,validation_data=(x_test, y_test), verbose=2)
    
    newRow = [i]
    newRow.append(score.history['loss'][29])
    newRow.append(score.history['acc'][29])
    newRow.append(score.history['mae'][29])
    newRow.append(score.history['mse'][29])
    newRow.append(score.history['val_loss'][29])
    newRow.append(score.history['val_acc'][29])
    newRow.append(score.history['val_mae'][29])
    newRow.append(score.history['val_mse'][29])
    
    newDF = pd.DataFrame([newRow],columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse']) 
    df = pd.concat([df,newDF])
    
    del(newRow)
    del(newDF)
    gc.collect()
    
    newRow = [i]
    newRow.append(score.history['loss'][-1])
    newRow.append(score.history['acc'][-1])
    newRow.append(score.history['mae'][-1])
    newRow.append(score.history['mse'][-1])
    newRow.append(score.history['val_loss'][-1])
    newRow.append(score.history['val_acc'][-1])
    newRow.append(score.history['val_mae'][-1])
    newRow.append(score.history['val_mse'][-1])
    
    newDF = pd.DataFrame([newRow],columns=['dropout','loss', 'acc', 'mae', 'mse', 'val_loss', 'val_acc', 'val_mae', 'val_mse']) 
    df2 = pd.concat([df2,newDF])
    
    del(model)
    del(score)
    del(newRow)
    del(newDF)
    gc.collect()
    clear_output(wait=True)
    print(count)
    count += 1
print("FINISHED")

9
FINISHED

In [35]:
df

,dropout,loss,acc,mae,mse,val_loss,val_acc,val_mae,val_mse
0,0.0,0.259787,0.930314,0.026198,0.010878,0.512817,0.862439,0.037774,0.020318
0,0.1,0.293381,0.913715,0.029119,0.012823,0.463351,0.870045,0.036937,0.019099
0,0.2,0.343759,0.897020,0.033440,0.015101,0.463790,0.865627,0.037761,0.019420
0,0.3,0.385037,0.885130,0.036879,0.016880,0.461545,0.864897,0.038690,0.019386
0,0.4,0.459824,0.861706,0.043576,0.020179,0.485319,0.857675,0.041417,0.020525
0,0.5,0.572542,0.824372,0.053489,0.025213,0.531057,0.841426,0.047339,0.022760
0,0.6,0.680169,0.792675,0.062167,0.029675,0.568401,0.834242,0.052654,0.024336
0,0.7,1.178259,0.608324,0.102438,0.049961,0.945391,0.740742,0.089654,0.039628
0,0.8,1.707808,0.390215,0.140678,0.069454,1.536563,0.509412,0.134865,0.062382
0,0.9,2.240576,0.188091,0.177200,0.088551,2.219244,0.195874,0.176982,0.088044

In [36]:
df.to_csv('Results-SVHN.csv', index=False)
df2.to_csv('Results2-SVHN.csv', index=False)

In [37]:
df2

,dropout,loss,acc,mae,mse,val_loss,val_acc,val_mae,val_mse
0,0.0,0.259787,0.930314,0.026198,0.010878,0.512817,0.862439,0.037774,0.020318
0,0.1,0.276211,0.920171,0.027575,0.012070,0.454488,0.872964,0.035385,0.018580
0,0.2,0.306591,0.908500,0.030101,0.013487,0.453132,0.870352,0.036115,0.018870
0,0.3,0.330783,0.901020,0.032097,0.014619,0.440382,0.872580,0.035708,0.018282
0,0.4,0.385545,0.884503,0.036659,0.016946,0.450900,0.869046,0.037538,0.018971
0,0.5,0.463112,0.861133,0.043077,0.020265,0.472333,0.859750,0.040860,0.020098
0,0.6,0.537186,0.837913,0.049174,0.023411,0.497165,0.854141,0.043454,0.021012
0,0.7,0.903101,0.705653,0.080499,0.039036,0.695675,0.821912,0.068062,0.029432
0,0.8,1.445588,0.508525,0.120109,0.058786,1.259016,0.622465,0.110716,0.050848
0,0.9,2.212085,0.187286,0.174764,0.087332,2.166411,0.195874,0.174534,0.086012